### ISSUE TITLE
failed at gather_nd_op.cc  indices[15,23] = [15, -1] does not index into param shape [16,24]

### ISSUE THREAD

**Issue by otakusbear** [iriscxy/Unified-Timeline-Summarizer#2]
当我运行run_summarization.py时，报错`2024-01-16 19:37:43.610554: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15,23] = [15, -1] does not index into param shape [16,24]
2024-01-16 19:37:43.610554: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15,23] = [15, -1] does not index into param shape [16,24]
2024-01-16 19:37:43.610554: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15,23] = [15, -1] does not index into param shape [16,24]
2024-01-16 19:37:43.610554: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at gather_nd_op.cc:47 : Invalid argument: indices[15,23] = [15, -1] does not index into param shape [16,24]
Traceback (most recent call last):
  File "/home/xss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/xss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/xss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[15,23] = [15, -1] does not index into param shape [16,24]`我按照readme文件所述的先执行了data_process.py，通过运行make_dict得到了vocab.txt，为什么会出现上述错误，麻烦您有空指点一下

**Comment by otakusbear** [comment]
我意识到是由于我的cuda版本过新，无法在tensorflow1.x中使用gpu，在使用cpu下的等效处理后解决了这一问题，但在训练了2个epoch后出现了损失为nan的情况loss: nan | ext_loss: nan | con_loss: nan | acc: 0.463 | time: 2.289，我没有改动超参数

**Comment by otakusbear** [comment]
能否提供您在event数据集上训练好的模型参数，感谢！

**Comment by otakusbear** [comment]
我解决了以上的大部分问题，但我发现在3090上训练了接近30k steps后仍然无法达到预期的结果，我猜测这可能与我的vocab.txt有关，因为结果中出现了很多UNK，我试过很多方式构造vocab，基于所有的event数据集上的json文件的输入输出字段构建，但效果不佳，请问您在中文数据集event和celebrity上的vocab.txt文件是如何构建的，基于字or基于单词？词表大小如何？我在基于单词构造的50k大小的词表中得到了最好的结果，但仍然不足以消除全部的UNK，您是否在中文数据集上使用了更大的词表？?感谢！

**Comment by iriscxy** [comment]
你好，请问输入是否有经过分词？可以检查一下输入单词是否成功映射成ID？训练loss是否有下降？词表大小50k应该足够了。

**Comment by otakusbear** [comment]
> 你好，请问输入是否有经过分词？可以检查一下输入单词是否成功映射成ID？训练loss是否有下降？词表大小50k应该足够了。

您好，我采用的是您提供的event和celebrity数据集，它们看起来似乎已经经过了分词？并且我使用您提供的data_process/make_dict.py 在训练集上构建vocab.txt文件（我不确定您在make_dict.py中使用的
```
# all_words = jdata[k].split() if isinstance(jdata[k], str) else ' '.join(jdata[k]).split()
all_words = list(jdata[k]) if isinstance(jdata[k], str) else list(' '.join(jdata[k]))
```
这两行是否有不同的用途，但我在使用注释掉的一行构建vocab时得到的是分词后的单词词表，超过50k大小，而非注释时则是独立汉字，不足50k)，训练时loss下降得非常缓慢。

**Comment by Artrainzy** [comment]
> 你好，请问输入是否有经过分词？可以检查一下输入单词是否成功映射成ID？训练loss是否有下降？词表大小50k应该足够了。

您好，请问获取到的中文数据集是经过编码之后的吗？看起来不是原来的文本？{"\u7ecf\u5386": ["1984 \u5e74 \uff0c \u62c5\u4efb \u7eba\u7ec7 \u79d1\u5b66 \u7814\u7a76\u9662 \u9662\u957f \uff08 - 1987 \u5e74 2 \u6708 \uff09 \uff0c \u5728 \u4ed6 \u7684 \u4efb\u671f \u5185 \uff0c \u7814\u7a76\u9662 \u7684 \u5b9e\u9a8c \u8bbe\u65bd \u5efa\u8bbe \u5f97\u5230 \u6062\u590d \u548c \u5b8c\u5584 \uff0c \u660e\u786e\u63d0\u51fa \u4e86 \u628a \u7814\u7a76\u9662 \u5efa\u8bbe \u6210\u4e3a \u7eba\u7ec7\u5de5\u4e1a \u79d1\u7814 \u961f\u4f0d \u4e2d \u7684 \u56fd\u5bb6\u961f \u7684 \u76ee\u6807 \u3002", "1987 \u5e74 10 \u6708 \uff0c \u7eba\u7ec7 \u5de5\u4e1a\u90e8 \u6210\u7acb \u79d1\u5b66\u6280\u672f\u59d4\u5458\u4f1a \uff0c \u6885\u81ea \u5f3a\u8c03 \u4efb \u79d1\u6280\u59d4 \u5e38\u52a1\u526f \u4e3b\u4efb \uff0c \u4e3b\u6301 \u65e5\u5e38 \u5de5\u4f5c \u3002", "1990 \u5e74 \uff0c \u7531 \u4ed6 \u7275\u5934 \u7ec4\u7ec7 \u7814\u5236\u6210\u529f \u7684 \u7eb1\u7ebf \u6761 \u5e72 \u5747\u5300\u5ea6 \u6d4b\u8bd5\u4eea \uff0c \u83b7 \u56fd\u5bb6 \u79d1\u6280\u8fdb\u6b65 \u4e8c\u7b49\u5956 \u3002", "1992 \u5e74 11 \u6708 \uff0c \u5f53\u9009 \u4e3a \u4e2d\u56fd \u7eba\u7ec7 \u5de5\u7a0b \u5b66\u4f1a \u526f\u7406\u4e8b\u957f \u3001 \u540d\u8a89 \u526f\u7406\u4e8b\u957f \u3001 \u5b66\u672f \u59d4\u5458\u4f1a \u4e3b\u4efb \u3002", "1995 \u5e74 \uff0c \u5f53\u9009 \u4e3a \u4e2d\u56fd\u5de5\u7a0b\u9662 \u9662\u58eb \uff0c \u96b6\u5c5e\u4e8e \u73af\u5883 \u4e0e \u8f7b\u7eba \u5de5\u7a0b \u5b66\u90e8 \uff08 \u7eba\u7ec7 \u5de5\u7a0b \uff09 \u3002", "1997 \u5e74 \uff0c \u9999\u6e2f \u6851\u9ebb \u57fa\u91d1\u4f1a \u59d4\u6258 \u4e2d\u56fd \u7eba\u7ec7 \u5de5\u7a0b \u5b66\u4f1a \u8bc4\u9009 \u6851 \u9ebb\u7eba\u7ec7 \u79d1\u6280\u5956 \uff0c \u6885 \u81ea\u5f3a \u8d1f\u8d23 \u8bc4\u9009 \u5de5\u4f5c \u3002", "2010 \u5e74 8 \u6708 19 \u65e5 \uff0c \u6885 \u81ea\u5f3a \u56e0\u75c5 \u5728 \u5317\u4eac \u53bb\u4e16 \uff0c \u4eab\u5e74 81 \u5c81 \u3002"], "\u59d3\u540d": "\u6885\u81ea\u5f3a", "\u7b80\u4ecb": ["1987 \u5e74 \u8c03\u4efb \u7eba\u7ec7 \u5de5\u4e1a\u90e8 \u79d1\u5b66\u6280\u672f\u59d4\u5458\u4f1a \u5e38\u52a1\u526f \u4e3b\u4efb \uff0c \u4e3b\u6301 \u65e5\u5e38 \u5de5\u4f5c \uff1b", "1992 \u5e74 \u5f53\u9009 \u4e3a \u4e2d\u56fd \u7eba\u7ec7 \u5de5\u7a0b \u5b66\u4f1a \u526f\u7406\u4e8b\u957f \u3001 \u5b66\u672f \u59d4\u5458\u4f1a \u4e3b\u4efb \uff1b", "1995 \u5e74 \u5f53\u9009 \u4e3a \u4e2d\u56fd\u5de5\u7a0b\u9662 \u9662\u58eb \uff1b", "1997 \u5e74 \u8d1f\u8d23 \u6851 \u9ebb\u7eba\u7ec7 \u79d1\u6280\u5956 \u8bc4\u9009 \u5de5\u4f5c \uff1b"]}这是celebrity中的test.json文件中的数据，请问是已经经过处理了吗？或者您可以提供下原来的数据集，又或者可以提供对应的vocab.txt

**Comment by iriscxy** [comment]
你好，这两个代码是针对不同语言和输入格式使用的。不要用独立汉字作为词表，而是使用分词的词组作为词表，选择频率最高的50k单词即可。
